# ЗАМЕНИТЬ НА СВОИ ПАРАМЕТРЫ!!!

server:
  port: 8080
  servlet:
    context-path: /api

spring:
  security:
    user:
      name: admin
      password: admin
  application:
    name: orchestra-api
  datasource:
    url: jdbc:postgresql://localhost:5433/orchestra_db
    username: postgres
    password: nisan852
  jpa:
    hibernate:
      ddl-auto: update  # Will create/update schema automatically
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
  sql:
    init:
      mode: never  # Don't auto-run schema.sql (use ddl-auto instead)

logging:
  level:
    com.orchestra.api: DEBUG
    org.hibernate.SQL: DEBUG